# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 04f7ac746771d59af78e8e8545e0d0b1264eb207e936eb9e9f60ae4a6fd4996f0b6b006d4e5b89ac1344c6fd4c6bf9cf8a47822c2ee8003d45832835c830c1e4
  watson_user: '8cafaaca-078c-4a04-9284-fc18e5aee509'
  watson_password: 'PIg0Uu6vngsp'
  # watson_user: '5ba2e73d-e916-4e67-b8c4-ae864dd46b96'
  # watson_password: '8hiM2ciYbYx4'
  twitter_consumer_key: 'yATl1briH5Bj4leyOlEcrO1n7'
  twitter_consumer_secret: 'Tv4WCVbWvRan8RO4PgZAOx7kNhVa6yQoyfMbFm3UvQw30GfPIZ'
  twitter_access_token: '977183846461591552-IxCdhZkbIdfMmRoYzHJQXuPqYJ6eTzZ'
  twitter_access_token_secret: 'EZMoBS9pTTZjMmxbKcQg8Pyvj9ol6fH9ektzbtVQ0sIw4'
  # twitter_consumer_key: 'RLD1Y7mGXBF5jmVs3ZQKxEc1L'
  # twitter_consumer_secret: 'aT0AJVNN8Yy6C6KPjHqqKTGXG53QENal3IGLyRbSrRkgYZWjEM'
  # twitter_access_token: '2997557823-UJTvgRfWjwzBaowKwPNjH9JtApksambKgoB9hgO'
  # twitter_access_token_secret: '852KWEqWxZAj5CHMTx7NgJvN1Vc1iRGB4a64jZgjR26IB'

test:
  secret_key_base: ba68121a6b0dbd4d576ddc2deec6e0df6b1d7d999ae1eb100e6272aa825ad4b0fcf24c0d5801c2d649298d2403015e4f2e98402e52be1a591c07561f364b1a42
  watson_user: '8cafaaca-078c-4a04-9284-fc18e5aee509'
  watson_password: 'PIg0Uu6vngsp'
  # watson_user: '5ba2e73d-e916-4e67-b8c4-ae864dd46b96'
  # watson_password: '8hiM2ciYbYx4'
  twitter_consumer_key: 'yATl1briH5Bj4leyOlEcrO1n7'
  twitter_consumer_secret: 'Tv4WCVbWvRan8RO4PgZAOx7kNhVa6yQoyfMbFm3UvQw30GfPIZ'
  twitter_access_token: '977183846461591552-IxCdhZkbIdfMmRoYzHJQXuPqYJ6eTzZ'
  twitter_access_token_secret: 'EZMoBS9pTTZjMmxbKcQg8Pyvj9ol6fH9ektzbtVQ0sIw4'
  # twitter_consumer_key: 'RLD1Y7mGXBF5jmVs3ZQKxEc1L'
  # twitter_consumer_secret: 'aT0AJVNN8Yy6C6KPjHqqKTGXG53QENal3IGLyRbSrRkgYZWjEM'
  # twitter_access_token: '2997557823-UJTvgRfWjwzBaowKwPNjH9JtApksambKgoB9hgO'
  # twitter_access_token_secret: '852KWEqWxZAj5CHMTx7NgJvN1Vc1iRGB4a64jZgjR26IB'

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  watson_user: <%= ENV["WATSON_USER"] %>
  watson_password: <%= ENV["WATSON_PASSWORD"] %>
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  twitter_access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
  twitter_access_token_secret: <%= ENV["TWITTER_ACCESS_TOKEN_SECRET"] %>
